name = "shrtnr"
main = "src/index.ts"
compatibility_date = "2026-03-30"
upload_source_maps = true

[observability]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "shrtnr-db"
migrations_dir = "migrations"
